// FIX: Provide definition for the Screen enum used for navigation.
export enum Screen {
  LANDING = 'LANDING',
  ONBOARDING_PHONE = 'ONBOARDING_PHONE',
  LOGIN = 'LOGIN',
  DASHBOARD = 'DASHBOARD',
  QR_SCAN = 'QR_SCAN',
  TRANSACTION_HISTORY = 'TRANSACTION_HISTORY',
  ANALYTICS = 'ANALYTICS',
  SECURITY = 'SECURITY',
  LOANS = 'LOANS',
  SAVINGS = 'SAVINGS',
  INSURANCE = 'INSURANCE',
  PAYMENT_GATEWAY = 'PAYMENT_GATEWAY',
  // FIX: Add missing screen definitions for Send Money and Pay Bills flows to resolve navigation errors.
  SEND_MONEY = 'SEND_MONEY',
  SEND_MONEY_CONFIRM = 'SEND_MONEY_CONFIRM',
  SEND_MONEY_SUCCESS = 'SEND_MONEY_SUCCESS',
  PAY_BILLS = 'PAY_BILLS',
  PAY_BILLS_CONFIRM = 'PAY_BILLS_CONFIRM',
  PAY_BILLS_SUCCESS = 'PAY_BILLS_SUCCESS',
}