// FIX: Provide definition for the Screen enum used for navigation.
export enum Screen {
  LANDING = 'LANDING',
  ONBOARDING_PHONE = 'ONBOARDING_PHONE',
  LOGIN = 'LOGIN',
  DASHBOARD = 'DASHBOARD',
  QR_SCAN = 'QR_SCAN',
  TRANSACTION_HISTORY = 'TRANSACTION_HISTORY',
  ANALYTICS = 'ANALYTICS',
  SECURITY = 'SECURITY',
  LOANS = 'LOANS',
  SAVINGS = 'SAVINGS',
  INSURANCE = 'INSURANCE',
  PAYMENT_GATEWAY = 'PAYMENT_GATEWAY',
  
  // --- NEW ADVANCED SCREENS ---
  QUANTUM_ADVISOR = 'QUANTUM_ADVISOR',
  CRYPTO_WALLET = 'CRYPTO_WALLET',
  COMMUNITY_BANKING = 'COMMUNITY_BANKING',
  GOALS = 'GOALS',
  MERCHANT_PORTAL = 'MERCHANT_PORTAL',
  FINANCIAL_EDUCATION = 'FINANCIAL_EDUCATION',

  // --- NEW NEXT-LEVEL SCREENS ---
  FUTURE_HUB = 'FUTURE_HUB',
  IMPACT_INVESTING = 'IMPACT_INVESTING',
  FINANCIAL_GAMING = 'FINANCIAL_GAMING',
  METAVERSE_BANK = 'METAVERSE_BANK',
  BIO_FINANCE = 'BIO_FINANCE',
  BACKEND_DASHBOARD = 'BACKEND_DASHBOARD',

  // FIX: Add missing screen enum values to support Send Money and Pay Bills flows.
  SEND_MONEY = 'SEND_MONEY',
  SEND_MONEY_CONFIRM = 'SEND_MONEY_CONFIRM',
  SEND_MONEY_SUCCESS = 'SEND_MONEY_SUCCESS',
  PAY_BILLS = 'PAY_BILLS',
  PAY_BILLS_CONFIRM = 'PAY_BILLS_CONFIRM',
  PAY_BILLS_SUCCESS = 'PAY_BILLS_SUCCESS',
}